name: Build Cannagrow App

on:
  workflow_dispatch:  # Permite ejecutar manualmente el flujo
  push:  # Ejecuta el flujo cuando haya un push
  pull_request:  # Ejecuta el flujo en pull requests

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow  # Establece el directorio de trabajo en la carpeta de la aplicación
    steps:
      - uses: actions/checkout@v4  # Usamos la versión 4 de la acción de checkout para obtener el código fuente

      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4  # Configura el JDK 23.0.1 de Temurin
        with:
          distribution: 'temurin'
          java-version: '23.0.1'

      - name: Build with Maven
        run: mvn clean package  # Ejecuta Maven para compilar y empaquetar la aplicación

      - name: Run Tests
        run: mvn test  # Ejecuta las pruebas unitarias

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4  # Sube los artefactos generados para Linux
        with:
          name: linux-build  # Nombre del artefacto
          path: ./java/Cannagrow/target  # Ruta del directorio donde se encuentran los artefactos generados

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow  # Establece el directorio de trabajo en la carpeta de la aplicación
    steps:
      - uses: actions/checkout@v4  # Usamos la versión 4 de la acción de checkout para obtener el código fuente

      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4  # Configura el JDK 23.0.1 de Temurin
        with:
          distribution: 'temurin'
          java-version: '23.0.1'

      - name: Build with Maven
        run: mvn clean package  # Ejecuta Maven para compilar y empaquetar la aplicación

      - name: Run Tests
        run: mvn test  # Ejecuta las pruebas unitarias

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4  # Sube los artefactos generados para Windows
        with:
          name: windows-build  # Nombre del artefacto
          path: ./java/Cannagrow/target  # Ruta del directorio donde se encuentran los artefactos generados
