name: Build Cannagrow App

on:
  workflow_dispatch:
  push:
    branches: [ java ]
  pull_request:
    branches: [ java ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23.0.1'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Create executable JAR
        run: |
          mvn assembly:single
          ls -la target/

      - name: Install required packages for jpackage
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot binutils

      - name: Create Linux executable
        run: |
          mkdir -p target/linux-executable
          echo "Verificando archivos JAR en target:"
          ls -la target/
          if [ ! -f "target/Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar" ]; then
            if [ -f "target/Cannagrow-1.0-SNAPSHOT.jar" ]; then
              cp target/Cannagrow-1.0-SNAPSHOT.jar target/Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar
            else
              exit 1
            fi
          fi
          jpackage \
            --input target/ \
            --name Cannagrow \
            --main-jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class com.example.cannagrow.Main \
            --type deb \
            --app-version 1.0.0 \
            --vendor "Your Company" \
            --description "Cannagrow Application" \
            --dest target/linux-executable

      - name: Create README for usage
        run: |
          echo "# Cannagrow Linux Application" > target/README.md
          echo "## Cómo ejecutar la aplicación" >> target/README.md
          echo "### Opción 1: Ejecutar el JAR directamente" >> target/README.md
          echo '\n```bash\njava -jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar\n```' >> target/README.md
          echo "### Opción 2: Instalar el paquete .deb" >> target/README.md
          echo '\n```bash\nsudo dpkg -i linux-executable/cannagrow_1.0.0-1_amd64.deb\n```' >> target/README.md

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            ./java/Cannagrow/target/*.jar
            ./java/Cannagrow/target/linux-executable
            ./java/Cannagrow/target/README.md

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23.0.1'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package assembly:single

      - name: Run Tests
        run: mvn test

      - name: Download and extract Launch4j
        run: |
          Invoke-WebRequest -Uri "https://github.com/launch4j/launch4j/releases/download/3.14/launch4j-3.14-win32.zip" -OutFile launch4j.zip
          Expand-Archive launch4j.zip -DestinationPath launch4j

      - name: Create Windows executable using repository config
        run: |
          mkdir -p target/windows-executable
          echo "Verificando archivos JAR en target:"
          dir target\*.jar

          # Ensure dependencies JAR exists
          if (-not (Test-Path "target\Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar")) {
            if (Test-Path "target\Cannagrow-1.0-SNAPSHOT.jar") {
              Copy-Item "target\Cannagrow-1.0-SNAPSHOT.jar" -Destination "target\Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar"
            } else {
              exit 1
            }
          }

          # Use config from src/launch4j
          if (-not (Test-Path "src/launch4j/launch4j.xml")) {
            Write-Host 'launch4j.xml not found in src/launch4j'
            exit 1
          }
          Copy-Item "src/launch4j/launch4j.xml" -Destination "."

          # Run Launch4j
          & .\launch4j\launch4j.exe "launch4j.xml"

      - name: Create README for usage
        run: |
          @"
          # Cannagrow Windows Application

          ## Cómo ejecutar la aplicación

          ### Opción 1: Ejecutar el JAR directamente
          ```
          java -jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar
          ```

          ### Opción 2: Ejecutar el archivo .exe
          Doble clic en `target\Cannagrow.exe`
          "@ | Out-File -FilePath "target/README.md" -Encoding utf8

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            ./java/Cannagrow/target/*.jar
            ./java/Cannagrow/target/windows-executable
            ./java/Cannagrow/target/README.md
