name: Build Cannagrow App on Windows

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21.0.4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.4'  # Usamos Java 21.0.4

    - name: Build with Maven
      run: mvn clean package

    - name: Run Tests
      run: mvn test

    - name: Install Launch4j
      run: choco install launch4j  # Instala Launch4j usando Chocolatey

    - name: Add Launch4j to PATH
      run: |
        $env:PATH += ";C:\ProgramData\chocolatey\bin"  # Añade la ruta de Launch4j al PATH

    - name: Generate .exe with Launch4j
      run: launch4j ./java/Cannagrow/launch4j-config.xml  # Ejecuta Launch4j para generar el .exe

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: ./java/Cannagrow/target
