name: Build Cannagrow App on Windows

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21.0.4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.4'  # Usamos Java 21.0.4

    - name: Build with Maven
      run: mvn clean package

    - name: Run Tests
      run: mvn test

    - name: Verify jpackage installation
      run: |
        java --version
        jpackage --version  # Verifica si jpackage está disponible

    - name: List contents of target directory
      run: |
        # Asegúrate de que el archivo JAR con las dependencias está en la carpeta target
        dir ./target  # Ajusta según la ubicación correcta del directorio 'target'

    - name: Create .exe with jpackage
      run: |
        # Crea un ejecutable .exe con jpackage usando el nombre correcto del archivo JAR
        jpackage --input ./target --name CannagrowApp --main-jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar --main-class com.example.cannagrow.Main --type exe --win-dir-chooser --win-shortcut --win-menu

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: ./target
