name: Build and Package Cannagrow

on:
  push:
    branches:
      - java

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Paso 1: Revisar el código del repositorio
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'
          architecture: 'x64'

      # Paso 3: Ejecutar mvn clean install
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./java/Cannagrow
        shell: pwsh
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.7-6.0\x64
          JAVA_HOME_21_X64: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.7-6.0\x64

      # Paso 4: Crear el ejecutable con jpackage
      - name: Package with jpackage
        run: |
          jpackage --input target `
            --name CannagrowApp `
            --main-jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar `
            --main-class com.example.cannagrow.Main `
            --type exe `
            --win-dir-chooser `
            --win-shortcut `
            --win-menu
        shell: pwsh
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.7-6.0\x64
          JAVA_HOME_21_X64: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.7-6.0\x64

      # Paso 5: Subir los archivos generados a un release (opcional)
      - name: Upload the executable
        uses: actions/upload-artifact@v3
        with:
          name: CannagrowApp
          path: ./target/CannagrowApp.exe
