name: Build and Package Cannagrow

on:
  workflow_dispatch:
    branches:
      - java

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -X
        working-directory: ./java/Cannagrow

      - name: Download and extract JavaFX jmods
        run: |
          $zipPath = "./java/Cannagrow/javafx-jmods.zip"
          $destPath = "./java/Cannagrow/jmods"
          Invoke-WebRequest -Uri "https://download2.gluonhq.com/openjfx/21/openjfx-21_windows-x64_bin-jmods.zip" -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $destPath -Force
        shell: pwsh

      - name: Create executable with jpackage
        run: |
          $jmodsPath = Get-ChildItem -Path "./jmods" -Directory | Select-Object -ExpandProperty FullName
          
          # Incluye los módulos necesarios para HTTPS
          jlink --add-modules `
            java.base,java.desktop,java.logging,java.sql,java.naming,javafx.controls,javafx.fxml,java.net.http,jdk.crypto.ec `
            --module-path "$jmodsPath" `
            --output runtime `
            --strip-debug --no-header-files --no-man-pages --compress=2

          $jar = Get-ChildItem -Path "./target" -Filter "*with-dependencies*.jar" | Select-Object -First 1
          if (-not $jar) {
            Write-Host "No se encontró el JAR con dependencias. Abortando."
            exit 1
          }

          jpackage --input ./target `
                   --name CannagrowApp `
                   --main-jar $jar.Name `
                   --main-class com.example.cannagrow.Main `
                   --type exe `
                   --runtime-image runtime `
                   --win-dir-chooser `
                   --win-shortcut `
                   --win-menu `
                   --icon icono.ico `
                   --win-console `
                   --java-options "-Xms512m -Xmx1024m" `
                   --app-version "2.0.0" `
                   --verbose
        shell: pwsh
        working-directory: ./java/Cannagrow

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: CannagrowApp
          path: |
            ./java/Cannagrow/*.exe
            ./java/Cannagrow/CannagrowApp/**
