name: Build and Deploy Cannagrow

on:
  push:
    branches:
      - java  # Ejecuta solo cuando se haga push a la rama 'java'
  pull_request:
    branches:
      - java  # Ejecuta también en PR hacia la rama 'java'
  workflow_dispatch:  # Permite ejecutar el flujo manualmente

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23.0.1'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR Artifact (Linux)
        uses: actions/upload-artifact@v3  # Usando la versión más reciente de la acción
        with:
          name: Cannagrow-1.0-SNAPSHOT-linux
          path: target/Cannagrow-1.0-SNAPSHOT.jar  # Asegúrate de que el archivo JAR exista en esa ruta

  build-windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23.0.1'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR Artifact (Windows)
        uses: actions/upload-artifact@v3  # Usando la versión más reciente de la acción
        with:
          name: Cannagrow-1.0-SNAPSHOT-windows
          path: target/Cannagrow-1.0-SNAPSHOT.jar  # Asegúrate de que el archivo JAR exista en esa ruta
