name: Build Cannagrow App
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23.0.1'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
      - name: Run Tests
        run: mvn test
      - name: Create executable JAR
        run: |
          mvn clean compile assembly:single
      - name: Install required packages for jpackage
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot binutils
      - name: Create Linux executable
        run: |
          jpackage --input target/ \
            --name Cannagrow \
            --main-jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class com.mycompany.cannagrow.Main \
            --type deb \
            --app-version 1.0.0 \
            --vendor "Your Company" \
            --description "Cannagrow Application" \
            --dest target/linux-executable
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            ./java/Cannagrow/target/*.jar
            ./java/Cannagrow/target/linux-executable
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23.0.1'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
      - name: Run Tests
        run: mvn test
      - name: Create executable JAR
        run: |
          mvn clean compile assembly:single
      - name: Download Launch4j
        run: |
          Invoke-WebRequest -Uri https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-win32.zip/download -OutFile launch4j.zip
          Expand-Archive launch4j.zip -DestinationPath .
      - name: Create Windows executable
        run: |
          mkdir -p target/windows-executable
          # Create a Launch4j configuration file
          @"
          <launch4jConfig>
            <dontWrapJar>false</dontWrapJar>
            <headerType>gui</headerType>
            <jar>target/Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar</jar>
            <outfile>target/windows-executable/Cannagrow.exe</outfile>
            <errTitle>Cannagrow Error</errTitle>
            <cmdLine></cmdLine>
            <chdir></chdir>
            <priority>normal</priority>
            <downloadUrl>http://java.com/download</downloadUrl>
            <supportUrl></supportUrl>
            <stayAlive>false</stayAlive>
            <restartOnCrash>false</restartOnCrash>
            <manifest></manifest>
            <icon></icon>
            <jre>
              <path></path>
              <bundledJre64Bit>false</bundledJre64Bit>
              <bundledJreAsFallback>false</bundledJreAsFallback>
              <minVersion>11.0.0</minVersion>
              <maxVersion></maxVersion>
              <jdkPreference>preferJre</jdkPreference>
              <runtimeBits>64/32</runtimeBits>
            </jre>
          </launch4jConfig>
          "@ | Out-File -FilePath "launch4j.xml" -Encoding utf8
          
          # Run Launch4j to create the executable
          ./launch4j/launch4j.exe launch4j.xml
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            ./java/Cannagrow/target/*.jar
            ./java/Cannagrow/target/windows-executable
