name: Build Cannagrow App on Windows

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21.0.4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.4'  # Usamos Java 21.0.4

    - name: Build with Maven
      run: mvn clean package

    - name: Run Tests
      run: mvn test

    - name: Install jpackage (if necessary)
      run: |
        choco install jdk21  # Esto instalará JDK 21, que debería incluir jpackage

    - name: Verify jpackage installation
      run: |
        java --version
        jpackage --version  # Verifica si jpackage está disponible

    - name: Create .exe with jpackage
      run: |
        # Crea un ejecutable .exe con jpackage
        jpackage --input ./java/Cannagrow/target --name CannagrowApp --main-jar Cannagrow.jar --main-class com.cannagrow.Main --type exe --win-dir-chooser --win-shortcut --win-menu

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: ./java/Cannagrow/target
