name: Build and Deploy Cannagrow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23.0.1'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cannagrow-1.0-SNAPSHOT-linux
          path: target/Cannagrow-1.0-SNAPSHOT.jar

  build-windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23.0.1'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cannagrow-1.0-SNAPSHOT-windows
          path: target/Cannagrow-1.0-SNAPSHOT.jar
