name: Build and Package Cannagrow

on:
  push:
    branches:
      - java

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Configurar el entorno de Java
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin  # Usar temurin en lugar de adoptopenjdk
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success

      # Descargar dependencias con Maven
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: mvn clean install

      # Verificar que el JAR ha sido generado en el directorio 'target'
      - name: List target directory
        run: dir ./target

      # Crear un ejecutable .exe con jpackage
      - name: Package with jpackage
        run: |
          jpackage --input target \
            --name CannagrowApp \
            --main-jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class com.example.cannagrow.Main \
            --type exe \
            --win-dir-chooser \
            --win-shortcut \
            --win-menu
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.4-7.0.LTS\x64
          JAVA_HOME_21_X64: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.4-7.0.LTS\x64
