name: Build Cannagrow App

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23.0.1'

      - name: Set up Maven
        uses: actions/setup-maven@v1  # Cambié a la versión v1

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ./java/Cannagrow/target

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23.0.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23.0.1'

      - name: Set up Maven
        uses: actions/setup-maven@v1  # Cambié a la versión v1

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ./java/Cannagrow/target
