name: Build Cannagrow App

on:
  workflow_dispatch:
  push:
    branches: [ java ]
  pull_request:
    branches: [ java ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package assembly:single

      - name: Run Tests
        run: mvn test

      - name: Create Linux executable (.deb)
        run: |
          mkdir -p target/linux-executable
          if [ ! -f "target/Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar" ]; then
            cp target/Cannagrow-1.0-SNAPSHOT.jar target/Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar
          fi
          sudo apt-get update && sudo apt-get install -y fakeroot binutils
          jpackage --input target/ \
                   --name Cannagrow \
                   --main-jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar \
                   --main-class com.example.cannagrow.Main \
                   --type deb \
                   --app-version 1.0.0 \
                   --vendor "Your Company" \
                   --description "Cannagrow Application" \
                   --dest target/linux-executable

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            ./java/Cannagrow/target/*.jar
            ./java/Cannagrow/target/linux-executable

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package assembly:single

      - name: Run Tests
        run: mvn test

      - name: Create Windows executable
        shell: powershell
        run: |
          mkdir -Path "target\windows-executable" -Force
          
          # Verify that launch4j config exists
          if (-not (Test-Path "src\launch4j\launch4j.xml")) {
            throw "Required configuration file src\launch4j\launch4j.xml does not exist"
          }
          
          # Ensure the jar exists
          $jar = "target\Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar"
          if (-not (Test-Path $jar)) { 
            Write-Host "JAR with dependencies not found, copying regular JAR"
            Copy-Item "target\Cannagrow-1.0-SNAPSHOT.jar" -Destination $jar 
          }
          
          # Use the launch4j from the repository
          $launch4jExe = "tools\launch4j-3.50-win32\launch4j.exe"
          if (Test-Path $launch4jExe) {
            Write-Host "Using Launch4j 3.50 from repository: $launch4jExe"
            & $launch4jExe "src\launch4j\launch4j.xml"
          } else {
            throw "Could not find launch4j.exe in the repository at $launch4jExe"
          }
          
          # Verify the executable was created
          if (Test-Path "target\windows-executable\Cannagrow.exe") {
            Write-Host "EXE created successfully"
          } else {
            throw "Failed to create Cannagrow.exe"
          }

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: ./java/Cannagrow/target/windows-executable/Cannagrow.exe
