name: Build Cannagrow App on Windows

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21.0.4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.0.4'  # Usamos Java 21.0.4

    - name: Build with Maven
      run: mvn clean package

    - name: Run Tests
      run: mvn test

    - name: Install Launch4j
      run: choco install launch4j -y  # Instala Launch4j usando Chocolatey, -y para auto-confirmar

    - name: Verify Launch4j Installation
      run: |
        echo "Verificando la instalación de Launch4j..."
        dir "C:\ProgramData\chocolatey\bin"  # Verifica si Launch4j está en esta ruta

    - name: Show Launch4j in PATH
      run: echo $Env:PATH  # Muestra el PATH para verificar si Launch4j está incluido

    - name: Generate .exe with Launch4j
      run: |
        # Intenta ejecutar Launch4j usando la ruta completa
        & "C:\ProgramData\chocolatey\bin\launch4j.exe" "./java/Cannagrow/launch4j-config.xml"  
        # Si el paso anterior no funciona, asegúrate de que la ruta es la correcta

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: ./java/Cannagrow/target
