name: Build and Package

on:
  push:
    branches:
      - java  # O la rama que estés utilizando
  pull_request:
    branches:
      - java

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Configurar Java 17 (o cualquier versión que prefieras)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'
      
      # Instalar Maven
      - name: Install Maven
        run: choco install maven

      # Limpiar y empaquetar con Maven
      - name: Build project with Maven
        run: mvn clean package -DskipTests

      # Verificar el contenido del directorio target
      - name: List target directory
        run: dir target/

      # Buscar el archivo .jar con dependencias generado en target
      - name: Get JAR file
        id: jar-file
        run: |
          $jarFile = Get-ChildItem -Path target -Filter "*-jar-with-dependencies.jar" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          echo "JAR_FILE=$($jarFile.FullName)" >> $GITHUB_ENV

      # Crear el .exe usando jpackage
      - name: Create executable with jpackage
        run: |
          jpackage --input target \
                   --name CannagrowApp \
                   --main-jar ${{ env.JAR_FILE }} \
                   --main-class com.example.cannagrow.Main \
                   --type exe \
                   --win-dir-chooser \
                   --win-shortcut \
                   --win-menu
