name: Build Cannagrow App (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - java
  pull_request:
    branches:
      - java

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./java/Cannagrow

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21.0.4
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.4'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Show target directory contents
        run: Get-ChildItem -Path ./target

      - name: Create .exe with jpackage
        run: |
          jpackage `
            --input ./target `
            --name CannagrowApp `
            --main-jar Cannagrow-1.0-SNAPSHOT-jar-with-dependencies.jar `
            --main-class com.example.cannagrow.Main `
            --type exe `
            --win-dir-chooser `
            --win-shortcut `
            --win-menu
        shell: pwsh
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          JAVA_HOME_21_X64: ${{ env.JAVA_HOME }}

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ./java/Cannagrow/target
