name: Build and Package Cannagrow (Ubuntu)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el código del repositorio
      - name: Check out code
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK 21 (Temurin)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Paso 3: Ejecutar mvn clean install
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./java/Cannagrow
        shell: bash

      # Paso 4: Verificar existencia del JAR
      - name: Find JAR file
        run: |
          echo "Buscando archivos JAR en ./java/Cannagrow/target"
          find ./java/Cannagrow/target -name "*.jar"
        shell: bash

      # Paso 5: Descargar y extraer JavaFX jmods
      - name: Download JavaFX jmods
        run: |
          mkdir -p ./java/Cannagrow/jmods
          wget https://download2.gluonhq.com/openjfx/21/openjfx-21_linux-x64_bin-jmods.zip -O ./java/Cannagrow/javafx-jmods.zip
          unzip -o ./java/Cannagrow/javafx-jmods.zip -d ./java/Cannagrow/jmods
          echo "Contenido de jmods:"
          ls -R ./java/Cannagrow/jmods
        shell: bash

      # Paso 6: Crear runtime y empaquetar
      - name: Package with jpackage
        run: |
          jmods_path=$(find ./java/Cannagrow/jmods -type d -name "javafx-jmods-21")
          echo "Ruta a los jmods: $jmods_path"

          cd ./java/Cannagrow

          jlink --add-modules java.base,java.desktop,javafx.controls,javafx.fxml,javafx.graphics \
                --module-path "$jmods_path" \
                --output runtime \
                --strip-debug \
                --no-header-files \
                --no-man-pages \
                --compress=2

          echo "Contenido del target:"
          ls -l ./target/*.jar

          jpackage --input ./target \
            --name CannagrowApp \
            --main-jar Cannagrow-1.0-SNAPSHOT.jar \
            --main-class com.example.cannagrow.Main \
            --type app-image \
            --runtime-image runtime \
            --app-version "1.0.0" \
            --verbose
        shell: bash

      # Paso 7: Subir artefacto
      - name: Upload the package
        uses: actions/upload-artifact@v4
        with:
          name: CannagrowApp
          path: ./java/Cannagrow/CannagrowApp/**
